#page title
page_title                                : Superate                                  

# App Info
ios_app_id                                : 1506182559                                

appstore_link                             : https://apps.apple.com/tr/app/id1506182559                                         
playstore_link                            :                                           
presskit_download_link                    : 
                                                                                      

app_icon                                  : assets/appicon.png                        
app_name                                  : Superate                                          
app_price                                 :                                           
app_description                           : Superate automagically turns your text and visuals into stunning designs

enable_smart_app_banner                   : true                                      



# Information About Yourself
your_name                                 : Apperto
your_link                                 : https://emilbaehr.com                     
your_city                                 : Istanbul
email_address                             : superate@apperto.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : No Design Skills Required
    description                           : Just provide your text, photos or videos to the app and it will generate a list of different designs automatically.
    fontawesome_icon_name                 : magic
    
  - title                                 : iPhone Device Preview
    description                           : Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name                 : mobile

  - title                                 : Video Support
    description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome_icon_name                 : play-circle

  - title                                 : Automatic Icon and Metadata
    description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
    fontawesome_icon_name                 : sync

  - title                                 : Easy to Tweak
    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Feature List
    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : star

  - title                                 : Smart App Banner
    description                           : Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Social Links
    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : link

  - title                                 : FontAwesome Support
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown